M48
; DRILL file {KiCad 5.99.0-unknown-b10f156dd0~130~ubuntu20.04.1} date Wed Jun 23 21:40:00 2021
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-06-23T21:40:00+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,5.99.0-unknown-b10f156dd0~130~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X6.1047Y-3.4178
X6.1047Y-3.6453
T0
M30
